### ISSUE TITLE
Don't say "I'll send you a Direct Message with details" when a user does "!help" via DM

### ISSUE THREAD

**Issue by lexicalunit** [lexicalunit/spellbot#121]
It's not needed b/c obviously you're already in a DM with the bot.

**Comment by crookedneighbor** [comment]
I'll take a look at this.

**Comment by lexicalunit** [comment]
Further clarification w/ screenshot of the issue: https://github.com/lexicalunit/spellbot/pull/131#issuecomment-667418834
