### ISSUE TITLE
Add Pauper Commander Support

### ISSUE THREAD

**Issue by camclark** [lexicalunit/spellbot#1753]
**Is your feature request related to a problem? Please describe.**
Pauper Commander (Pauper EDH) is not available
![image](https://github.com/user-attachments/assets/4cce41c2-01b3-4c84-954e-73d59e2ed8d0)

But it is available in spell table:
![image](https://github.com/user-attachments/assets/fcdbf493-3796-43f1-8730-22bef11139ae)

**Describe the solution you'd like**
`/lfg format` works with `Pauper EDH`, spawning 

**Describe alternatives you've considered**
None, sorry

**Additional context**
Pauper Commander is also supported at the competitive level:
https://cpdh.guide/

**Comment by lexicalunit** [comment]
Thanks for the addition, @camclark! Your changes are live now:

<img width="413" alt="Screenshot 2024-10-28 at 1 29 46 PM" src="https://github.com/user-attachments/assets/0cd19379-2e53-41a8-baf8-4aea66b4ff3a">

Please note that I don't have any way to tell SpellTable what format is selected by SpellBot. Unfortunately the SpellTable API doesn't allow me to send that data over to them, even though I have it and would love to be able to send it to them. 😢

**Comment by lexicalunit** [comment]
@camclark I'm adding an update today that will make it so that the format selected in SpellBot is set in the SpellTable game that gets created! 🎉
