### ISSUE TITLE
Allow config option to 'listen' to commands from other bots

### ISSUE THREAD

**Issue by ransby** [lexicalunit/spellbot#427]
Would you be willing to add an admin config option to allow commands from other bots? I have no idea if most other servers have a good use-case for that but I know it would help a lot on ours to integrate with our existing functionality. I don't see where the message capturing happens (as mentioned before I have only rudimentary code reading skills) but I see you're testing for it:

@pytest.mark.parametrize("channel_type", ["dm", "text"])
async def test_on_message_from_a_bot(self, client, channel_maker, channel_type):
 channel = channel_maker.make(channel_type)
 await client.on_message(MockMessage(BOT, channel, "!spellbot help"))
 assert len(channel.all_sent_calls) == 0

I know very little about discord API so if there are reasons this isn't a good idea please lmk :)

Thanks for the great bot!!

**Comment by lexicalunit** [comment]
@ransby Sounds like a cool idea! Can you give me an example of how it might work? Is this happening because you have two bots on your server and they both have the same command?

**Comment by ransby** [comment]
Sorry for the delay in getting back to you.

Yeah, our desire for that feature is in part because of shared commands.
!lfg is already in use by our existing pairing functionality, which is
basically just glorified role assignment without any spelltable
integration. If I can augment the existing functionality by using MEE6's
advanced commands to have our current play commands additionally shoot out
Spellbot commands to take advantage of the spelltable integration, I can
kind of tack on functionality without having to do a big @everyone post
explaining changes to the webcam magic commands.

As silly as it is, our MEE6 bot (which we named Tinybones) has its own
'cult' and religious hierarchy on the channel and part of my desire to
allow Tinybones to call Spellbot is to retain our user's interaction with
it. I have no intention of trying to cut Spellbot out of the equation - my
intention is that commands for Tinybones that cause it to send commands to
Spellbot would not hide the Spellbot response nor disguise the fact that
Spellbot is the one doing the heavy lifting; it's just that from a
cosmetics perspective it's appealing to retain the character of Tinybones
as the primary point of interaction.

Hope that helps!

Tyler

**Comment by ransby** [comment]
# Ignore !help because so many other bots use it, use `!spellbot help` instead.
        if request.startswith("help"):
            return
Too true we're using like 5 different command prefixes now. Made me chuckle.

**Anyway** found the place where the bot check is happening in the on_message method(function?procedure? idk)    __init__.py line 947:
async def on_message(self, message: discord.Message) -> None:
 """Behavior when the client gets a message from Discord."""
 try:
 author = cast(discord.User, message.author)

 # don't respond to any bots
 if author.bot:
 return

So this would need a boolean server-level config added in the class Server(Base): as a new column, presumably like

other_bot_commands_enabled = Column(Boolean, nullable=False, server_default=false())

...and then I guess all it would take is 

 # don't respond to any bots
 if author.bot and not other_bot_commands_enabled:
 return


So I was pretty much just poking around to see if I could find it but I know full well you could have found it faster and I presume it's more a question of if you want to allow this behavior in your bot in the first place. I don't know if I've captured it all - particularly I'm not sure if the config settings have to be added to a class somewhere rather than just added in the Server(Base): settings area, but if you want me to fork and make these two changes and send a pull request I'm happy to do so.

**Comment by lexicalunit** [comment]
I could probably just remove the following lines from the codebase:

```
# don't respond to any bots
if author.bot:
    return
```

They were added just to prevent the potential abuse of someone writing a bot that could DDoS SpellBot by automatically making lots of requests to it. However an attacker can already do this by creating a Discord bot that does not report itself honestly as a bot... so I'm not sure this protection is really doing anything besides making your use case difficult.

**Comment by ransby** [comment]
That's both true and a much easier change; the only downside being there is
no opt-out option in that case. I don't have enough experience to know if
there are other discord servers where that might cause trouble. My instinct
is that there aren't, or if there are it could be managed by assigning or
not assigning the spellbot admin role to their own bots, but that is an
assumption 🤷‍♂️

**Comment by lexicalunit** [comment]
@ransby Ok this is deployed! Let me know if it's working for you :)

**Comment by ransby** [comment]
Of _course_ when I go to test it the MEE6 site is offline so I can't add the more complex commands in the dashboard. Ah well. I've verified that the bot-to-bot commands are indeed working:
![image](https://user-images.githubusercontent.com/47725075/115773620-87885e00-a37e-11eb-9bf4-cb8d9c6edb9b.png)
