### ISSUE TITLE
Start a game with fewer than the default game size.

### ISSUE THREAD

**Issue by cflasche25** [lexicalunit/spellbot#506]
I would like the option to add like a !start command to start a game with less than the default game size. For example, if we have the default game size set to 4 and only have 3 people, we'd like the option to just send a command and have Spellbot start the game, create a voice channel and a Spelltable link.

**Comment by lexicalunit** [comment]
Thanks for creating an issue for this @cflasche25!

One thing I always worry about with a new feature is how it might be abused. I think maybe this would be ok if only the people that are in the game have the ability to start their own game. That way some jerk couldn't come in and start someone else's game.

🤔 Maybe `!start` could work. Or maybe there could be a button on the game post for "Start this game now" or something?

Another workaround for now is to have everyone leave the game, and then run:

```
!lfg size:3 @someone @another
```

Which would automatically create and start a 3 player game with yourself and the other two mentioned players.

**Comment by lexicalunit** [comment]
Note to self: This could maybe be done by adding a button to non-started games that says "Start Game Now" which only players in the game should be able to successfully interact with.

**Comment by wise-io** [comment]
My comment on #617 would work for this too.

**Comment by lexicalunit** [comment]
Yep. One thing I'm concerned about is potential for abuse. Like a jerk could join a game, and then start it immediately, and then not join the SpellTable game. And just keep doing that over and over. I guess if someone did that they'd get banned from the server pretty quickly tho. So maybe it's not that big of an issue.

**Comment by wise-io** [comment]
> Yep. One thing I'm concerned about is potential for abuse. Like a jerk could join a game, and then start it immediately, and then not join the SpellTable game. And just keep doing that over and over. I guess if someone did that they'd get banned from the server pretty quickly tho. So maybe it's not that big of an issue.

There is definitely potential for abuse. However, doesn't your existing /block command address this? You could also leave the game joinable if there are still empty seats. I'd rely on those safeguards, as well as good server moderation to control the potential abuse. Discord's upcoming Timeout functionality may also help address this in the future.

That said, I'm happy to see that you're making abuse prevention a high priority!

**Comment by wise-io** [comment]
**Another note:** If you do end up allowing a user to join multiple games simultaneously, it would increase the risk of abuse here.

**Comment by lexicalunit** [comment]
There's also nothing stopping users from just... going to spelltable.com and creating a game themselves and DMing each other the link. If they were fed up waiting for a 4th person to show up, they could just do that.

Another idea: What if I have it so if a game is sitting at 3 players for more than 20 minutes, the bot would message the people in the game and ask them if they wanted to just start the game with 3 players now. They could respond directly in the DM with "yes" or "no" and if everyone says "yes" then the game will start immediately with 3 players.

**Comment by wise-io** [comment]
> There's also nothing stopping users from just... going to spelltable.com and creating a game themselves and DMing each other the link. If they were fed up waiting for a 4th person to show up, they could just do that.

This is what my playgroup does currently. Or we use your suggested workaround and change the seats. 

> Another idea: What if I have it so if a game is sitting at 3 players for more than 20 minutes, the bot would message the people in the game and ask them if they wanted to just start the game with 3 players now. They could respond directly in the DM with "yes" or "no" and if everyone says "yes" then the game will start immediately with 3 players.

This solution makes sense and would prevent abuse. The option to customize the timeout to different lengths per server with `/setup` would be nice as well!
