### ISSUE TITLE
Using the Leave button should only work for games that you're in

### ISSUE THREAD

**Issue by lexicalunit** [lexicalunit/spellbot#617]
If you click the Leave button on a game that you're not in, nothing should happen.

Also, there is some logic in Join/LFG that handles is edit_origin fails. Similar logic should probably be implemented for Leave/leave.

**Comment by wise-io** [comment]
You could check to see if the user is mentioned in the interaction embed before executing the Leave button code. If not, display a ephemeral reply.

**Comment by lexicalunit** [comment]
> You could check to see if the user is mentioned in the interaction embed before executing the Leave button code. If not, display a ephemeral reply. Of course, you may already have a better way figured out by now.

Yep I was thinking something like this might work. Though it's also kind of nice that you can hit any leave button to leave any game that you're in. That way it's super easy to leave a game. You don't have to go find the one your in.

But then... there is the `/leave` command too, which you could use without having to hunt down your game. So maybe that's good enough?

**Comment by wise-io** [comment]
> > You could check to see if the user is mentioned in the interaction embed before executing the Leave button code. If not, display a ephemeral reply. Of course, you may already have a better way figured out by now.
> 
> Yep I was thinking something like this might work. Though it's also kind of nice that you can hit any leave button to leave any game that you're in. That way it's super easy to leave a game. You don't have to go find the one your in.
> 
> But then... there is the `/leave` command too, which you could use without having to hunt down your game. So maybe that's good enough?

I like that the leave button and command works for any game. The only way I could see this not being sufficient is if SpellBot allows you to be registered for multiple games at once (does it?). 

**Example Case:**
> User joins 3 games (all not full), hoping to get a game in ASAP. Game 1 fills up, so he wants to leave the other two games.

Does the /leave command or any other leave button work correctly in this case?

**Comment by lexicalunit** [comment]
> I like that the leave button and command works for any game. The only way I could see this not being sufficient is if SpellBot allows you to be registered for multiple games at once (does it?).

It doesn't currently, but I have been playing with the idea of allowing this to some extent. It's just a thought at this point though.
