### ISSUE TITLE
/Spectators Option for /LFG

### ISSUE THREAD

**Issue by wise-io** [lexicalunit/spellbot#682]
**Is your feature request related to a problem? Please describe.**
Currently, SpellBot sends a link to spectate a game directly to the members who are playing the game. This isn't very useful because it's only visible to players already in the game.

**Describe the solution you'd like**
I'd like a /Spectators Boolean option added to the `/LFG` command. When set to true, it would add a Spectate button link to the original LFG interaction embed for users to join and spectate. It would also allow other discord users to join the voice channel if the relevant option is enabled. Ideally, the created voice channel would match the permissions of the text channel/thread `/LFG` was originally used in.

**Describe alternatives you've considered**
Add a SpellBot server setting to set the default behavior for this option. If set to enabled, the above functionality would apply to all games created with SpellBot.

**Comment by lexicalunit** [comment]
Hi @wise-io, thanks for the issue report! Would it be possible to use the `Toggle Public Links` feature of the `/setup` command to turn on the `Public Links` setting on your server?

**Used the `/setup` command:**
![Screen Shot 2021-12-07 at 9 51 19 AM](https://user-images.githubusercontent.com/1903876/145080729-3445e559-b6c6-4b66-9a80-9a1ab3696e78.png)

**Clicked the `Toggle Public Links` button:**
![Screen Shot 2021-12-07 at 9 52 46 AM](https://user-images.githubusercontent.com/1903876/145080956-5c2fb2ec-08e5-4d75-9b00-c0e0155e07a6.png)

And now when I use `/lfg` in a channel, the links (voice, game, and spectate) are all visible directly in the channel:
![Screen Shot 2021-12-07 at 9 54 03 AM](https://user-images.githubusercontent.com/1903876/145081155-33d55701-f53d-436c-9bb1-de06bb8b9b05.png)

This feature is off by default as a way of combating abuse. In some guilds users will harass others by constantly joining their games to shout at them. When the links are only shown in direct messages, it prevents this kind of harassment.

Note that admins have another option for finding information about a game, even if `Public Links` is off. They can use the `/info` command to get details. For example, if I run `/info game_id: SB221496` I get:
![Screen Shot 2021-12-07 at 9 57 45 AM](https://user-images.githubusercontent.com/1903876/145081761-c7e13cae-6cb0-4301-a07a-0ec18166f291.png)

Do these features resolve this issue for you?

**Comment by wise-io** [comment]
Holy cow. Not sure how I missed this functionality. Thank you for responding and sorry for wasting your time with this issue!
Thanks again for the awesome bot!
