### ISSUE TITLE
Already in a game

### ISSUE THREAD

**Issue by WhiskeyRant** [lexicalunit/spellbot#711]
Spellbot tells me I'm already in a game even though I haven't joined or signed up for any games.

**Comment by lexicalunit** [comment]
You should be able to run the `/leave` command resolve the issue. Discord was having some issues so your user may have been in a weird state. Hopefully this doesn't happen too often.

**Comment by WhiskeyRant** [comment]
Ok thanks for the reply

**Comment by lexicalunit** [comment]
I think this should be resolved with the latest version of the bot.
