### ISSUE TITLE
Ability to use Placeholders in MOTD

### ISSUE THREAD

**Issue by 20BBrown14** [lexicalunit/spellbot#741]
**Is your feature request related to a problem? Please describe.**
Not a feature breaking problem. But some of the servers that use Spellbot require some sort of game submission for tracking and what not. Usually they require the submission to be a specific format. Placeholders in the MOTD dictating the format with prefilled values would be cool. See more below.

**Describe the solution you'd like**
It'd be very cool if, as an admin, I could use placeholders in the MOTD strings that would be replaced with values in the MOTD display. For instance, I could set the MOTD string to `Game - SB${sb_game_id} ${player_1_full_name}: First Place ${player_2_full_name}: Second place, ${player_3_full_name}: Third Place, ${player_4_full_name}`

And the display would be something like `Game - SB123456 John#123: First Place, Apple#456: Second Place, User#000: Third place, Jack#757: Fourth Place`

**Describe alternatives you've considered**
Of course the template can be added an the values filled in by the user. However, the bot has these values so it'd be nice if, as an admin, I could use them in the MOTD

**Additional context**
Some values that I think should be available using placeholders
SB Game ID
Game Format
Game start time/date
Players (seperated)

**Comment by lexicalunit** [comment]
Cool idea! Wouldn't be difficult to add either :)

**Comment by lexicalunit** [comment]
Sorry for the long wait. I was just starting my new job when you made this ticket. I finally have some free time to spend on SpellBot today :)
